### ISSUE TITLE
Change vs code icons in alfred

### ISSUE THREAD

**Issue by viktorkrepak** [Acidham/alfred-vscode-workspace-explorer#3]
I propose to update icons from alfred output based on new VS logo. 
<img width="720" alt="CleanShot 2022-08-08 at 16 04 47@2x" src="https://user-images.githubusercontent.com/27999815/183424666-842e98a8-0071-4bf1-8146-27ead16a788e.png">

**Comment by Acidham** [comment]
I would like to have different icons for differentiating VSCode app and Workflow. If you prefer to get the same icon just replace the one in WF directory with your preferred icon.
